# Site settings
title: MisterTofu
email: tebesu at gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mistertofu.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username:  MisterTofu

# Build settings
markdown: kramdown
