# Site settings
title: Travis - Blog
email: tebesu [ham only please AT] gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tebesu.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username:  tebesu

# Build settings
markdown: kramdown
